### ISSUE TITLE
adding the schema plugin in geonetwork 3.2.0

### ISSUE THREAD

**Issue by aandry** [metadata101/iso19139.mcp-2.0#2]
hello,
I know it is not the place for geonetwork management but I would like to know if anyone have already  integrated schema plugin into geonetwork 3.2.0. 

I tried to put the folder containing xsd/xsl (plugin/iso19139.mcp-2.0) in geonetwork's schema_plugins folder. Geonetwork successfully scanned the new plugin and load templates but i can't create new record based on this template (xsl errors from server side).

Am i wrong working  this way ? Cause other way would be modifying geonetwork pom.xml, integrate this plugin like new module in the project and recreate geonetwork's war... this seems to me a strange way to simply add a new schema plugin.

thanks

**Comment by sylviefiat** [comment]
Hi, I have the same problem and logs is showing :
`# Error at xsl:call-template on line 14 column 51 of utility-tpl.xsl:`
`#   XTSE0650: No template exists named get-iso19139-title`
`# 2017-02-14 06:53:56,973 ERROR [jeeves] - Error occurred within a transaction`
`# javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.`
`# 	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)`
`#	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)`
`# at de.fzi.dbs.xml.transform.CachingTransformerFactory.newTransformer(CachingTransformerFactory.java:120)` 
(etc.)
Somthing to change in xml schema ? 
Anyone help ?
thanks
